global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "vllm"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - "localhost:8000" # Change this to the appropriate host and port if needed